version: '3'
services:
  web:
    environment:
      AITAWS_SETTINGS: "/app/env/docker.env"
    build: .
    ports:
      - "8090:80"
    restart: always
    volumes:
      - ${PWD}/aitaws/prod.db:/app/aitaws/prod.db
